[package]
name = "memcpy"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
libc = "0.2"

[[bench]]
name = "memcpy"
harness = false

[[test]]
name = "memcpy"
path = "benches/memcpy.rs"
